In [89]:
import pandas as pd
from pathlib import Path

In [90]:
DATA_DIR = Path.cwd().parent / "data"
INPUT_FILE = DATA_DIR / "student_dropout_dataset_v3.csv"
OUTPUT_FILE = DATA_DIR / "base_tratada_v2.csv"

df = pd.read_csv(INPUT_FILE)

In [91]:
df.head()

,Student_ID,Age,Gender,Family_Income,Internet_Access,Study_Hours_per_Day,Attendance_Rate,Assignment_Delay_Days,Travel_Time_Minutes,Part_Time_Job,Scholarship,Stress_Index,GPA,Semester_GPA,CGPA,Semester,Department,Parental_Education,Dropout
0,1,22.1,Male,25000.0,Yes,3.36,86.1,2,20.4,Yes,No,5.5,0.96,0.90,0.90,Year 1,Arts,High School,0
1,2,20.7,Male,25000.0,Yes,4.30,68.0,2,44.0,No,No,6.8,1.28,1.20,1.19,Year 3,Engineering,Bachelor,1
2,3,22.4,Male,40183.0,Yes,4.40,70.9,0,48.9,Yes,No,5.5,1.68,1.32,1.32,Year 1,Arts,Master,0
3,4,24.4,Male,NaN,Yes,NaN,82.2,2,38.6,No,No,NaN,1.78,1.77,1.77,Year 1,CS,High School,1
4,5,20.5,Female,25319.0,Yes,4.19,75.7,1,23.0,No,No,7.0,1.48,0.91,0.87,Year 4,Business,Bachelor,0

In [92]:
# Total de alunos
len(df)

10000

In [93]:
# Total de alunos que desistiram
df.Dropout.sum()

np.int64(2354)

Para evitar enviesar os dados, preenchendo com mediana, estou propondo a remoção de linhas com valores nulos e logo verificando se foram retirados muitos dados de alunos que saíram (Métrica alvo).
No total foram removidas 236 linhas de estudantes que abandonaram seus cursos.

Outra possibilidade preencher os valores medianos tirando como base outra coluna, por exemplo, no caso da escolaridade, baseado nos alunos que **saíram**, preencher com a moda.

In [94]:
df.isnull().sum()

Student_ID                 0
Age                        0
Gender                     0
Family_Income            500
Internet_Access            0
Study_Hours_per_Day      500
Attendance_Rate            0
Assignment_Delay_Days      0
Travel_Time_Minutes        0
Part_Time_Job              0
Scholarship                0
Stress_Index             500
GPA                        0
Semester_GPA               0
CGPA                       0
Semester                   0
Department                 0
Parental_Education       511
Dropout                    0
dtype: int64

In [95]:
df_sem_nulos = df.dropna()

In [96]:
# Verificando quantos alunos foram removidos que saíram = 236
df_sem_nulos.Dropout.sum()

np.int64(2118)

In [97]:
# Verificando se sobraram valores nulos
df_sem_nulos.isnull().sum()

Student_ID               0
Age                      0
Gender                   0
Family_Income            0
Internet_Access          0
Study_Hours_per_Day      0
Attendance_Rate          0
Assignment_Delay_Days    0
Travel_Time_Minutes      0
Part_Time_Job            0
Scholarship              0
Stress_Index             0
GPA                      0
Semester_GPA             0
CGPA                     0
Semester                 0
Department               0
Parental_Education       0
Dropout                  0
dtype: int64

In [98]:
len(df_sem_nulos)

9020

In [99]:
# Verificando se apenas tem Yes ou No
df_sem_nulos['Internet_Access'].unique()

<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

In [100]:
# Forma de contar valores e mostra caso tenha null
df['Internet_Access'].value_counts(dropna=False)

Internet_Access
Yes    8769
No     1231
Name: count, dtype: int64

In [101]:
mapeamento_yes_no = {'Yes': 1, 'No': 0}
df_sem_nulos['Internet_Access'] = df_sem_nulos['Internet_Access'].map(mapeamento_yes_no) # convertendo a coluna de acesso a internet
df_sem_nulos['Part_Time_Job'] = df_sem_nulos['Part_Time_Job'].map(mapeamento_yes_no) # convertendo a coluna de trabalho meio periodo
df_sem_nulos['Scholarship'] = df_sem_nulos['Scholarship'].map(mapeamento_yes_no) # convertendo a coluna de bolsa de estudos

In [102]:
df_sem_nulos = pd.get_dummies(df_sem_nulos, columns=['Department'])

In [103]:
df_sem_nulos.head()

,Student_ID,Age,Gender,Family_Income,Internet_Access,Study_Hours_per_Day,Attendance_Rate,Assignment_Delay_Days,Travel_Time_Minutes,Part_Time_Job,...,Semester_GPA,CGPA,Semester,Parental_Education,Dropout,Department_Arts,Department_Business,Department_CS,Department_Engineering,Department_Science
0,1,22.1,Male,25000.0,1,3.36,86.1,2,20.4,1,...,0.90,0.90,Year 1,High School,0,True,False,False,False,False
1,2,20.7,Male,25000.0,1,4.30,68.0,2,44.0,0,...,1.20,1.19,Year 3,Bachelor,1,False,False,False,True,False
2,3,22.4,Male,40183.0,1,4.40,70.9,0,48.9,1,...,1.32,1.32,Year 1,Master,0,True,False,False,False,False
4,5,20.5,Female,25319.0,1,4.19,75.7,1,23.0,0,...,0.91,0.87,Year 4,Bachelor,0,False,True,False,False,False
6,7,24.5,Male,25000.0,1,3.00,78.2,1,37.4,1,...,0.33,0.44,Year 4,Bachelor,0,False,False,True,False,False

In [104]:
df_sem_nulos.columns

Index(['Student_ID', 'Age', 'Gender', 'Family_Income', 'Internet_Access',
       'Study_Hours_per_Day', 'Attendance_Rate', 'Assignment_Delay_Days',
       'Travel_Time_Minutes', 'Part_Time_Job', 'Scholarship', 'Stress_Index',
       'GPA', 'Semester_GPA', 'CGPA', 'Semester', 'Parental_Education',
       'Dropout', 'Department_Arts', 'Department_Business', 'Department_CS',
       'Department_Engineering', 'Department_Science'],
      dtype='str')

In [105]:
df_sem_nulos.isnull().sum()

Student_ID                0
Age                       0
Gender                    0
Family_Income             0
Internet_Access           0
Study_Hours_per_Day       0
Attendance_Rate           0
Assignment_Delay_Days     0
Travel_Time_Minutes       0
Part_Time_Job             0
Scholarship               0
Stress_Index              0
GPA                       0
Semester_GPA              0
CGPA                      0
Semester                  0
Parental_Education        0
Dropout                   0
Department_Arts           0
Department_Business       0
Department_CS             0
Department_Engineering    0
Department_Science        0
dtype: int64

In [ ]:
df_sem_nulos.Parental_Education.unique()

<ArrowStringArray>
['High School', 'Bachelor', 'Master', 'PhD']
Length: 4, dtype: str

In [ ]:
mapeamento_educacao = {
    'High School': 0,
    'Bachelor': 1,
    'Master': 2,
    'PhD': 3
}

df_sem_nulos['Parental_Education'] = df_sem_nulos['Parental_Education'].map(mapeamento_educacao)

In [ ]:
df_sem_nulos.isnull().sum()

Student_ID                0
Age                       0
Gender                    0
Family_Income             0
Internet_Access           0
Study_Hours_per_Day       0
Attendance_Rate           0
Assignment_Delay_Days     0
Travel_Time_Minutes       0
Part_Time_Job             0
Scholarship               0
Stress_Index              0
GPA                       0
Semester_GPA              0
CGPA                      0
Semester                  0
Parental_Education        0
Dropout                   0
Department_Arts           0
Department_Business       0
Department_CS             0
Department_Engineering    0
Department_Science        0
dtype: int64

In [ ]:
df_sem_nulos.to_csv(OUTPUT_FILE, index=False)

In [ ]:
new_df = pd.read_csv(OUTPUT_FILE)

new_df.head()

,Student_ID,Age,Gender,Family_Income,Internet_Access,Study_Hours_per_Day,Attendance_Rate,Assignment_Delay_Days,Travel_Time_Minutes,Part_Time_Job,...,Semester_GPA,CGPA,Semester,Parental_Education,Dropout,Department_Arts,Department_Business,Department_CS,Department_Engineering,Department_Science
0,1,22.1,Male,25000.0,1,3.36,86.1,2,20.4,1,...,0.90,0.90,Year 1,0,0,True,False,False,False,False
1,2,20.7,Male,25000.0,1,4.30,68.0,2,44.0,0,...,1.20,1.19,Year 3,1,1,False,False,False,True,False
2,3,22.4,Male,40183.0,1,4.40,70.9,0,48.9,1,...,1.32,1.32,Year 1,2,0,True,False,False,False,False
3,5,20.5,Female,25319.0,1,4.19,75.7,1,23.0,0,...,0.91,0.87,Year 4,1,0,False,True,False,False,False
4,7,24.5,Male,25000.0,1,3.00,78.2,1,37.4,1,...,0.33,0.44,Year 4,1,0,False,False,True,False,False